import { useEffect, useState } from "react";
import { useParams } from "react-router";
import { Typography } from "@mui/material";
import Editor from "@monaco-editor/react";
import { getPublicSnippet } from "../services/snippet.service";


type Snippet = {
  _id: string;
  title: string;
  language: string;
  code: string;
};

export default function PublicSnippet() {
  const { id } = useParams();
  const [snippet, setSnippet] = useState<Snippet | null>(null);

  useEffect(() => {
    if (id) {
      getPublicSnippet(id).then((res) => setSnippet(res.data));
    }
  }, [id]);

  if (!snippet) return null;

  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4">
      <div className="max-w-[1000px] mx-auto">
        <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-2xl">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
            <div>
              <Typography variant="h4" className="font-extrabold text-slate-800 leading-tight">
                {snippet.title}
              </Typography>
              <Typography className="text-slate-500 font-mono mt-1 text-sm">
                {snippet.language}
              </Typography>
            </div>
            <div className="px-4 py-2 bg-blue-50 text-[#1a73e8] rounded-xl font-bold text-sm border border-blue-100 uppercase tracking-widest self-start md:self-center">
              Public Snippet
            </div>
          </div>

          <div className="rounded-2xl overflow-hidden border border-slate-200 shadow-inner">
            <Editor
              height="600px"
              language={snippet.language}
              value={snippet.code}
              theme="vs-dark"
              options={{
                readOnly: true,
                fontSize: 14,
                minimap: { enabled: false },
                scrollBeyondLastLine: false,
                padding: { top: 20, bottom: 20 }
              }}
            />
          </div>

          <div className="mt-8 pt-8 border-t border-slate-100 flex justify-between items-center">
            <Typography className="text-slate-400 text-xs">
              Generated by OAuth Snippets
            </Typography>
            <div className="flex gap-2">
              <div className="w-2 h-2 rounded-full bg-red-400" />
              <div className="w-2 h-2 rounded-full bg-amber-400" />
              <div className="w-2 h-2 rounded-full bg-emerald-400" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
